[project]
name = "demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jonathan Tremesaygues", email = "jonathan.tremesaygues@slaanesh.org" },
]
requires-python = ">=3.14"
dependencies = [
    "clai>=2.32.1",
    "pydantic-ai-slim[openai,web-fetch]>=2.32.1",
]

[dependency-groups]
dev = [
    "ipython>=9.16.1",
]
